#include "utils.h"

int main()
{
  scalar s[];
  origin (-0.5, -0.5, -0.5);
  // "../pdump/dump" is generated by pdump.c
  assert (restore (file = "../pdump/dump", list = {s}));
  output_cells (stdout);
  foreach()
    assert (s[] == sin(x)*cos(y));
}
