#include "utils.h"

int main (int argc, char * argv[])
{
  init_grid (N);
  scalar s[];
  origin (-0.5, -0.5, -0.5);
  // "restore.dump" is generated by pdump.c
  char name[80];
  strcpy (name, argv[0]);
  strcat (name, ".dump");
  assert (restore (file = name, list = {s}));
  output_cells (stdout);
  foreach()
    assert (s[] == sin(x)*cos(y));
}
