#include <stdio.h>
#include <string.h>

#define N 7

int main (int argc, char ** argv)
{
  if (argc != 2) {
    fprintf (stderr, "usage: endfor FILE\n");
    return 1;
  }
  FILE * fp = fopen(argv[1], "r");
  if (fp == NULL) {
    perror (argv[1]);
    return 1;
  }

  char c, buf[N+1] = "";
  char foreachs[80]; int nforeachs = 0;
  char endforeachs[80]; int nendforeachs = 0;
  int n = 0, comment = 0, comments = 0, brack = 0, line = 1, foreach = 0, inforeach = 0;
  int endfor = 0, foreachbrack = 0, foreachpara = 0, preproc = 0, para = 0;

  printf ("/* DO NOT EDIT: this file was automatically generated by 'endfor'\n"
	  " * from '%s'. Edit it instead. */\n", argv[1]);
  printf ("# 1 \"%s\"\n", argv[1]);
  while ((c = fgetc(fp)) != EOF) {
    putchar(c);
    if (c == '\n')
      line++;

    if (n < N) {
      buf[n++] = c;
      buf[N] = '\0';
    }
    else {
      int i;
      for (i = 0; i < N - 1; i++)
	buf[i] = buf[i+1];
      buf[N-1] = c;
    }

    if (preproc) {
      if (c == '\n' && buf[n-2] != '\\')
	preproc = 0;
      continue;
    }
    else if (comment) {
      if (comments && c == '\n' && buf[n-2] != '\\')
	comment = comments = 0;
      else if (buf[n-2] == '*' && c == '/')
	comment = 0;
      continue;
    }

    if (foreach) {
      if ((c >= 'a' && c <= 'z') || c == '_')
	foreachs[nforeachs++] = c;
      else {
	foreachs[nforeachs++] = '\0';
	inforeach = 1; foreachbrack = brack; foreachpara = para;
	foreach = 0;
      }
    }
    if (endfor) {
      if ((c >= 'a' && c <= 'z') || c == '_')
	endforeachs[nendforeachs++] = c;
      else {
	endforeachs[nendforeachs++] = '\0';
	if (strcmp(&endforeachs[4], foreachs)) {
	  fprintf (stderr, 
		   "%s:%d: error: "
		   "foreach%s() loop ended with end_for%s()\n", 
		   argv[1], line, foreachs, endforeachs);
	  return 1;
	}
	endfor = 0; nendforeachs = 0;
      }
    }

    switch (c) {
    case ';':
      if (inforeach && brack == foreachbrack && para == foreachpara) {
	inforeach = 0;
	printf (" end_foreach%s(); ", foreachs);
      }
      break;
    case '#':
      preproc = 1;
      continue;
    case '*':
      if (buf[n-2] == '/') {
	comment = 1;
	continue;
      }
      break;
    case '/':
      if (buf[n-2] == '/') {
	comment = comments = 1;
	continue;
      }
      break;
    case '(': para++;  break;
    case ')': para--;  break;
    case '{': brack++; break;
    case '}':
      brack--;
      if (brack < 0) {
	fprintf (stderr, 
		 "%s:%d: error: mismatched bracket\n", argv[1], line);
	return 1;
      }
      if (inforeach && brack == foreachbrack) {
	inforeach = 0;
	printf (" end_foreach%s(); ", foreachs);
      }
      break;
    }

    if (!strncmp(buf, "end_for", 7)) {
      if (!inforeach) {
	fprintf (stderr, "%s:%d: error: no loop to end\n", argv[1], line);
	return 1;
      }
      inforeach = 0;
      endfor = 1;
    }
    else if (!endfor && !strncmp(buf, "foreach", 7)) {
      if (inforeach) {
	fprintf (stderr, "%s:%d: error: foreach() loops cannot be nested\n", argv[1], line);
	return 1;
      }
      foreach = 1; nforeachs = 0;
    }
  }
  if (brack != 0) {
    fprintf (stderr, "%s:%d: error: parse error at end of input (brack = %d)\n", 
	     argv[1], line, brack);
    return 1;
  }
  return 0;
}
