fputs ("%EventDef PajeDefineContainerType 1\n"
       "%  Alias string\n"
       "%  Type string\n"
       "%  Name string\n"
       "%EndEventDef\n"
       "%EventDef PajeDefineEventType 2\n"
       "%  Alias string\n"
       "%  Type string\n"
       "%  Name string\n"
       "%EndEventDef\n"
       "%EventDef PajeDefineStateType 3\n"
       "%  Alias string\n"
       "%  Type string\n"
       "%  Name string\n"
       "%EndEventDef\n"
       "%EventDef PajeDefineEntityValue 6\n"
       "%  Alias string\n"
       "%  Type string\n"
       "%  Name string\n"
       "%  Color color\n"
       "%EndEventDef \n"
       "%EventDef PajeCreateContainer 7\n"
       "%  Time date\n"
       "%  Alias string\n"
       "%  Type string\n"
       "%  Container string\n"
       "%  Name string\n"
       "%EndEventDef\n"
       "%EventDef PajeDestroyContainer 8\n"
       "%  Time date\n"
       "%  Name string\n"
       "%  Type string\n"
       "%EndEventDef \n"
       "%EventDef PajeSetState 10\n"
       "%  Time date\n"
       "%  Type string\n"
       "%  Container string\n"
       "%  Value string\n"
       "%EndEventDef\n"
       "%EventDef PajeNewEvent 11\n"
       "%  Time date\n"
       "%  Type string\n"
       "%  Container string\n"
       "%  Value string\n"
       "%EndEventDef\n"
       "1 Prog 0 \"Program\"\n"
       "1 Thread Prog \"Thread\"\n"
       "2 Event Thread \"Thread Event\"\n"
       "3 State Thread \"Thread State\"\n"
       "6 compute State \"compute\"  \"0 1 0\"\n"
       "6 rcv_pid_send State \"rcv_pid_send\" \"0 0 1\"\n"
       "6 rcv_pid_receive State \"rcv_pid_receive\" \"1 0 0\"\n"
       "6 mpi_all_reduce State \"mpi_all_reduce\" \"0 0.5 1\"\n"
       "6 mpi_boundary_match State \"mpi_boundary_match\" \"0 0.5 1\"\n"
       "6 mpi_boundary_sync State \"mpi_boundary_sync\" \"0.5 0 1\"\n"
       "6 mpi_boundary_update State \"mpi_boundary_update\" \"0.5 0.5 1\"\n"
       "7 0 C_Prog Prog 0 \"Program\"\n",
       tracefp);
