#!/bin/bash

AVCONV="`which avconv 2> /dev/null`"
if test -z "$AVCONV"; then
    AVCONV=`which ffmpeg`
fi

if test -z "$AVCONV"; then
    echo "ppm2ogv: warning: could not find 'avconv' or 'ffmpeg'" > /dev/stderr
    echo "ppm2ogv: the output will just be concatenated PPM files" \
	> /dev/stderr
    command=cat
    log=/dev/null
else
    # -r 15  '15 frames/sec'
    if test -d "$TMPDIR" ; then
	log=`mktemp $TMPDIR/ppm2ogv.XXXXXX`
	out=`mktemp $TMPDIR/ppm2ogv.XXXXXX`
    else
	log=`mktemp /tmp/ppm2ogv.XXXXXX`
	out=`mktemp /tmp/ppm2ogv.XXXXXX`
    fi
    while test $# -gt 0; do
	case $1 in
	    -r) shift; rate="-r $1" ;;
	esac
	shift
    done
    command="$AVCONV -f image2pipe -vcodec ppm $rate -i - -codec:v libtheora -qscale:v 7 -y -f ogg"
    while test $# -gt 0; do
	case $1 in
	    -r) shift ;;
	    *) command="$command $1" ;;
	esac
	shift
    done
fi

if $command $out 2> $log; then :
else
    cat $log > /dev/stderr
    rm -f $log $out
    exit 1
fi
cat $out
rm -f $log $out

exit 0
