#!/bin/bash

AVCONV="`which avconv`"
if test -z "$AVCONV"; then
    AVCONV=`which ffmpeg`
fi

if test -z "$AVCONV"; then
    echo "ppm2mp4: warning: could not find 'avconv' or 'ffmpeg'" > /dev/stderr
    echo "ppm2mp4: the output will just be concatenated PPM files" \
	> /dev/stderr
    command=cat
    log=/dev/null
else
    # -crf 18 low compression/high quality, 28 high compression/low quality
    # see https://trac.ffmpeg.org/wiki/Encode/H.264
    # -r 15  '15 frames/sec'
    if test -d "$TMPDIR" ; then
	log=`mktemp $TMPDIR/ppm2mp4.XXXXXX`
	out=`mktemp $TMPDIR/ppm2mp4.XXXXXX`
    else
	log=`mktemp /tmp/ppm2mp4.XXXXXX`
	out=`mktemp /tmp/ppm2mp4.XXXXXX`
    fi
    while test $# -gt 0; do
	case $1 in
	    -r) shift; rate="-r $1" ;;
	esac
	shift
    done
    command="$AVCONV -f image2pipe -vcodec ppm $rate -i - -c:v libx264 -preset slow -crf 18 -movflags +faststart -vf format=yuv420p -y -f mp4"
    while test $# -gt 0; do
	case $1 in
	    -r) shift ;;
	    *) command="$command $1" ;;
	esac
	shift
    done
fi

if $command $out 2> $log; then :
else
    cat $log > /dev/stderr
    rm -f $log $out
    exit 1
fi
cat $out
rm -f $log $out

exit 0
