#!/bin/bash

CONVERT="`which convert`"
GIFSICLE="`which gifsicle`"

if test -z "$CONVERT" -o -z "$GIFSICLE"; then
    echo "ppm2gif: warning: could not find 'convert' or 'gifsicle'" > /dev/stderr
    echo "ppm2gif: the output will just be concatenated PPM files" \
	 > /dev/stderr
    cat
else
    command="gifsicle --colors 256 --optimize --delay 5"
    while test $# -gt 0; do
	command="$command $1"
	shift
    done
    if test -d "$TMPDIR" ; then
	log=`mktemp $TMPDIR/ppm2gif.XXXXXX`
    else
	log=`mktemp /tmp/ppm2gif.XXXXXX`
    fi
    convert ppm:- $log-%04d.gif
    if $command $log-*.gif 2> $log; then :
    else
	cat $log > /dev/stderr
	rm -f $log*
	exit 1
    fi
    rm -f $log*
fi
